services:

  api-tests:
    image: ppodgorsek/robot-framework:latest
    user: root
    working_dir: /tests
    volumes:
      - .:/tests
      - ./results:/results
    command: >
      robot
      --listener allure_robotframework:/results/allure-results-api
      --outputdir /results/api
      api_tests

  ui-tests:
    image: ppodgorsek/robot-framework:latest
    user: root
    working_dir: /tests
    volumes:
      - .:/tests
      - ./results:/results
    command: >
      robot
      --listener allure_robotframework:/results/allure-results-ui
      --outputdir /results/ui
      ui_tests
